---


workflow:
  rules:
    - if: $CI_PIPELINE_SOURCE == "merge_request_event"
    - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS
      when: never
    - if: $CI_COMMIT_BRANCH


pre-commit:
  image: python:3.14
  before_script:
    - python -m pip install pre-commit
  script:
    - pre-commit run --all-files --show-diff-on-failure


pylint:
  image: python:3.14-trixie
  before_script:
    - apt-get --assume-yes --quiet update
    - >
      apt-get --assume-yes --quiet install --no-install-recommends
      libenchant-2-2
    - python -m pip install 'pylint[spelling]' pylint-gitlab
  script:
    - >
      pylint
      --output-format=pylint_gitlab.GitlabCodeClimateReporter:pylint.json,colorized
      '**/*.py'
  artifacts:
    reports:
      codequality: pylint.json


.build:
  stage: deploy
  image: python:3.14-trixie
  before_script:
    - apt-get --assume-yes --quiet update
    - >
      apt-get --assume-yes --quiet install --no-install-recommends
      graphviz
      latexmk
      tex-gyre
      texlive-fonts-recommended
      texlive-latex-extra
      texlive-latex-recommended
    - pip install tox
  script:
    - tox run -e build
    - cp -r build/html public


deploy-preview:
  extends: .build
  rules:
    - if: $CI_COMMIT_BRANCH != $CI_DEFAULT_BRANCH
  artifacts:
    paths:
      - public
  after_script:
    - echo "Preview at ${CI_ENVIRONMENT_URL}"
  environment:
    auto_stop_in: one hour
    deployment_tier: development
    name: review/$CI_COMMIT_REF_SLUG
    # yamllint disable-line rule:quoted-strings
    url: "https://${CI_PAGES_HOSTNAME}\
      /-/${CI_PROJECT_TITLE}/-/jobs/${CI_JOB_ID}/artifacts\
      /public/index.html"


deploy-pages:
  extends: .build
  rules:
    - if: $CI_COMMIT_BRANCH == $CI_DEFAULT_BRANCH
  pages: true


...  # EOF
