#


image: 'python:3.6'

pages:
    script:
        - 'pip install tox'
        - 'tox -e build'
        - 'cp -r build/html public'
    artifacts:
        paths:
            - 'public'
    only:
      - 'master'


# EOF
