#


language: 'python'

addons:
  apt:
    packages:
      - 'graphviz'

install:
  - 'pip install tox'

script:
  - 'tox -e build'
  - 'touch build/html/.nojekyll'

deploy:
  - provider: 'pages'
    skip_cleanup: true
    on:
      branch: 'master'
    local_dir: 'build/html'
    github_token: '${GITHUB_TOKEN}'


# EOF
