---


language: 'python'

addons:
  apt:
    packages:
      - 'graphviz'
      - 'latexmk'
      - 'texlive-fonts-recommended'
      - 'texlive-latex-extra'
      - 'texlive-latex-recommended'

install:
  - 'pip install tox'

script:
  - 'tox -e build'
  - 'touch build/html/.nojekyll'

deploy:
  - provider: 'pages'
    skip_cleanup: true
    on:
      branch: 'main'
    local_dir: 'build/html'
    github_token: '${GITHUB_TOKEN}'


... EOF
