#


[tox]
env_list =
    build
no_package = True


[testenv]
allowlist_externals =
    make
base_python = python3.14
commands =
    make
deps =
    -r requirements.txt
skip_install = True


[testenv:develop]
commands =
deps =
    Sphinx


# EOF
