---


name: 'main-workflow'
run-name: "Main workflow"

on:
  push:
  workflow_dispatch:

concurrency:
  group: 'pages'
  cancel-in-progress: true

jobs:

  'build-job':
    runs-on: 'ubuntu-22.04'
    steps:
      - name: "Install apt packages"
        run: |
          sudo apt-get --assume-yes --quiet update
          sudo apt-get --assume-yes --quiet install --no-install-recommends graphviz latexmk tex-gyre texlive-fonts-recommended texlive-latex-extra texlive-latex-recommended
      - name: "Setup Python"
        uses: 'actions/setup-python@v4'
        with:
          python-version: '3.10'
      - name: "Install tox"
        run: 'python -m pip install tox'
      - name: "Checkout"
        uses: 'actions/checkout@v3'
        with:
          fetch-depth: 0
      - name: "Build"
        run: 'tox run -e build'
      - name: "Upload artifact for Pages"
        if: "github.ref_name == 'main'"
        uses: 'actions/upload-pages-artifact@v1'
        with:
          path: 'build/html'

  'deploy-job':
    if: "github.ref_name == 'main'"
    needs: ['build-job']
    runs-on: 'ubuntu-22.04'
    permissions:
      contents: 'read'
      pages: 'write'
      id-token: 'write'
    environment:
      name: 'github-pages'
      url: '${{ steps.deployment.outputs.page_url }}'
    steps:
      - name: "Setup Pages"
        uses: 'actions/configure-pages@v3'
      - name: "Deploy to GitHub Pages"
        id: 'deployment'
        uses: 'actions/deploy-pages@v1'


...  # EOF
